### ISSUE TITLE
Potential issue with ROC_Accuracy_binary

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/the-segmentation-game#6]
Hi Martin @martinschatz-cz ,

I'm not sure if the metric ROC_Accuracy_binary is implemented correctly. I outlined these two regions and the value is too high, I would expect 0. Or am I misunderstanding the measure?

![image](https://user-images.githubusercontent.com/12660498/171989931-843db009-774d-423b-b7ca-9b7cdf1a0e44.png)

Let me know what you think!

Best,
Robert

**Comment by martinschatz-cz** [comment]
Hi Robert @haesleinhuepf ,

that is pitfall a of ROC accuracy, as it counts both true positive and true negative as hits. ACC = (TP + TN)/(TP+TN+FP+FN). So it works nicely in balanced sets (that are often used as examples). But it will give really bad feedback in real-world pixel-wise classification that we often use. I would like to add a section about it + it is a good reason to always look at the whole confusion table and not only the final metrics.

Cheers,
Martin

**Comment by haesleinhuepf** [comment]
Awesome, I was almost expecting something like me misinterpreting this.
